# Modelling {#modelling}

## Data pre-processing
With socio-demographic information now available for each electorate, each election is joined to the data  corresponding with its two-party preferred vote. Socio-demographic variables within each election year are standardized to have mean zero and variance one, to adjust for changing variable scales. For example, inflation-adjusted median rental prices increased across almost all electorates, with median rent of 200 dollars per week placing an electorate in the 90th percentile in 2001, but only the 30th percentile in 2016.

### Dimension reduction
With only $N = 150$ observations (electorates) in each election and $p = 65$ socio-demographic variables in each cross-section, any model using all variables would face serious problems with multi-collinearity and over-fitting, likely leading to erroneous conclusions regarding variable significance. Therefore a form of dimension reduction is adopted before models are fit. 

Socio-demographic variables[^2] that represent similar information are combined into "factors" using principal component analysis (PCA). The scree plots of the principal components for each election all level off after four components, and the loadings of these four components are similar across the elections. Principal components are then computed on the combined set of socio-demographics across all six elections. A factor is created by combining several variables all have large loadings in a particular component and when there is an intuitive reason as to why these variables could represent common information. A loading with magnitude greater than 0.15 is considered large. After computing these sums, each factor is again standardized to have mean zero and variance one, within each election. 

Consider the `Incomes` factor as an illustration. Independent of principal components, we may suspect that median personal income, median household income and median family income are providing similar information about the financial wellbeing of an electorate. Their loadings in the first principal component are large (0.20, 0.21 and 0.22 respectively), which provides the evidence needed to combine these variables into a single factor, which is called `Incomes`.

This process reduces the predictor set to $p = 30$.

[^2]: A preliminary step involved removing all age bands, because age is represented by median age, and to remove variables relating to particular denominations of Christianity.

## Model framework
An identical model specification is used across the six elections, with each election modelled separately. This allows for the socio-demographic effects to be estimated separately for each year, allowing for interpretation of temporal changes in these effects. This is preferable over a single longitudinal model because it avoids any concerns of undue bias stemming from an incorrectly imposed time-varying restriction on any variable. Without such restrictions, a pooled cross-sectional model does not yield any distinct advantage over separate cross-sections. The panel approach is avoided because of how frequently electoral boundaries change, meaning that electorates that have the same name across elections are not guaranteed to represent the same geographical region. Therefore any fixed or random effects models would be difficult to estimate without implementing consistent boundaries, which would requiring further imputation. 

For each cross-section, let the response variable be the two-party preferred vote in favour of the Liberal party, denoted $Y$, with $Y = 70$ representing a 70% preference for Liberal, 30% for Labor. Although $Y$ lies in the interval $(0,100)$, observed values are never very close to 0 or 100 (minimum $24.05 \%$ and maximum $74.90 \%$), so there is no need to impose the constraint of $Y \in [0,100]$. Furthermore, the response is found to be spatially correlated in each election (Moran's I test, $p \le 7\cdot10^{-15}$). This is expected, as electorates are aggregate spatial units, and hence the spatial structure of the data must modelled appropriately. 

The spatial error model [@Anselin88] is chosen because captures spatial heterogeneity by incorporating a spatially structured random effect vector [@LeSage2009]. In this context, the random effect can be thought of as capturing the unobserved political climate in each electorate, where the climate is correlated with the climate in neighbouring electorates. This functions under the assumption that the climate is independent of electoral socio-demographics, and that an electorate is equally correlated with any electorate that shares a part of its boundary. Spatial weights are calculated in accordance with these assumptions. The spatial error model is specified as follows:

Let $\rho$ be spatial autoregressive coefficient, $\boldsymbol v$ be a spherical error term, ${\boldsymbol W}$ be a matrix of spatial weights (containing information about the neighbouring regions), $\boldsymbol X$ be a matrix of socio-demographic covariates, $\boldsymbol \beta$ be a vector of regression coefficients and $\boldsymbol a$ be a spatially structured random effect vector.

$${\boldsymbol y} = {\boldsymbol X} {\boldsymbol \beta} + {\boldsymbol a}$$
and

$${\boldsymbol a} = \rho {\boldsymbol W} {\boldsymbol a} + {\boldsymbol v}$$
where 

$${\boldsymbol v} \sim N({\boldsymbol 0}, \sigma^2 {\boldsymbol I_n})$$.

so it can be written

$${\boldsymbol y} = {\boldsymbol X} {\boldsymbol \beta} + ({\boldsymbol I}_n-\rho {\boldsymbol W})^{-1}{\boldsymbol v}$$

Estimation is done using feasible generalized least squares.

Table 4.1 details the resultant estimated model coefficients and their estimated standard errors for each of the six elections. These are interpreted in the next section.

```{r printmodels, eval = F}
# Add rho and make adjustments to this
temp_fgls <- function(my_formula, my_data, sp_weights) {
  # Spatial weights matrix
  w_mat <- listw2mat(sp_weights)
  
  # Get OLS residuals
  ols_model <- lm(my_formula, my_data)
  my_res <- ols_model$residuals
  
  # Solve for rho
  res_model <- lm(my_res ~ w_mat%*%my_res)
  rho <- res_model$coefficients[2]
  rho_df <- data.frame(estimate = rho, se = summary(res_model)$coefficients[2,2], p = summary(res_model)$coefficients[2,4])
  
  # Transform data for GLS
  trans_mat <- diag(nrow(my_data)) - rho*w_mat
  gls_data <- data.frame(LNP_Percent = trans_mat %*% my_data$LNP_Percent,
    Intercept = trans_mat %*% rep(1,nrow(my_data))) %>% 
    bind_cols(as.data.frame(trans_mat %*% as.matrix(my_data %>% select(-LNP_Percent))))
  
  # GLS model
  my_formula <- formula(paste0(my_formula,  " - 1"))
  gls_model <- gls(my_formula, gls_data)
  
  return(gls_model)
}

# Models
full_formula = "LNP_Percent ~ ."

# 2016
glsmod16 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2016") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_16)

# 2013
glsmod13 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2013") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_13)

# 2010
glsmod10 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2010") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_10)

# 2007
glsmod07 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2007") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_07)

# 2004
glsmod04 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2004") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_04)

# 2001
glsmod01 <- temp_fgls(full_formula, 
  my_data = model_df %>% filter(year == "2001") %>% select(-c(DivisionNm, year)),
  sp_weights = sp_weights_01)

# Stargazer
stargazer::stargazer(glsmod16, glsmod13, glsmod10, glsmod07, glsmod04, glsmod01, header = FALSE, 
  column.sep.width = "1pt", 
  title = "Estimated model using the final set of predictor variables for each of the six elections.",
  dep.var.labels = "Two-party preferred vote in favor of the Liberal party", 
  font.size = "scriptsize", df = FALSE, digits = 2, 
  column.labels = c("2001", "2004", "2007", "2010", "2013", "2016"),
  notes = c("Estimated coefficients for variable named in column one shown for", "election year indicated by column heading, with estimated standard", "deviation for each coefficient shown below in parenthesis. Overall", "summary measures for each regression equation are provided in the", "bottom panel."),
  notes.align = "l")
```

\begin{table}[!htbp] \centering 
  \caption{Estimated model using the final set of predictor variables for each of the six elections.} 
  \label{} 
\scriptsize 
\begin{tabular}{@{\extracolsep{1pt}}lcccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\ 
\cline{2-7} 
\\[-1.8ex] & \multicolumn{6}{c}{Two-party preferred vote in favor of the Liberal party} \\ 
 & 2001 & 2004 & 2007 & 2010 & 2013 & 2016 \\ 
\\[-1.8ex] & (1) & (2) & (3) & (4) & (5) & (6)\\ 
\hline \\[-1.8ex] 
 $\rho$ & 0.48$^{***}$ & 0.29$^{*}$ & 0.15 & $-$0.04 & 0.15 & 0.44$^{***}$ \\ 
  & (0.16) & (0.16) & (0.17) & (0.19) & (0.17) & (0.15) \\ 
  & & & & & & \\ 
 AusCitizen & $-$1.53 & $-$0.87 & 1.00 & 0.67 & $-$2.83 & $-$2.77 \\ 
  & (2.95) & (2.90) & (2.93) & (2.57) & (2.63) & (2.51) \\ 
  & & & & & & \\ 
 Born\_Asia & $-$2.13 & $-$2.56 & $-$7.58$^{***}$ & $-$1.37 & 0.74 & 2.63 \\ 
  & (2.20) & (2.58) & (2.68) & (1.96) & (2.55) & (3.03) \\ 
  & & & & & & \\ 
 Born\_MidEast & $-$0.82 & 1.70 & 1.79 & 2.92$^{*}$ & 3.22$^{*}$ & 1.92 \\ 
  & (1.56) & (1.54) & (1.54) & (1.51) & (1.78) & (1.53) \\ 
  & & & & & & \\ 
 Born\_SE\_Europe & $-$1.63 & $-$1.25 & $-$1.72 & $-$0.20 & 0.04 & 1.02 \\ 
  & (0.99) & (1.15) & (1.34) & (1.17) & (2.05) & (2.34) \\ 
  & & & & & & \\ 
 Born\_UK & $-$1.37 & $-$0.35 & $-$0.29 & 0.29 & $-$0.87 & $-$0.49 \\ 
  & (0.98) & (1.00) & (1.05) & (0.80) & (0.90) & (1.04) \\ 
  & & & & & & \\ 
 BornElsewhere & 1.74 & 4.04 & 9.78$^{**}$ & 5.01 & $-$0.51 & $-$1.08 \\ 
  & (4.52) & (4.46) & (4.47) & (3.59) & (3.67) & (3.40) \\ 
  & & & & & & \\ 
 Buddhism & 1.51 & 1.09 & 2.41$^{*}$ & 0.90 & 2.84$^{*}$ & 1.50 \\ 
  & (1.24) & (1.25) & (1.40) & (1.25) & (1.61) & (1.94) \\ 
  & & & & & & \\ 
 Christianity & 5.17$^{**}$ & 3.08 & $-$0.60 & $-$1.93 & 3.44 & 0.53 \\ 
  & (2.52) & (2.79) & (3.44) & (3.45) & (4.19) & (4.58) \\ 
  & & & & & & \\ 
 CurrentlyStudying & $-$0.09 & 1.73 & 3.28$^{***}$ & 4.03$^{***}$ & 1.69 & $-$1.14 \\ 
  & (1.13) & (1.17) & (1.21) & (1.12) & (1.09) & (1.01) \\ 
  & & & & & & \\ 
 DeFacto & $-$11.02$^{***}$ & $-$9.73$^{***}$ & $-$8.60$^{***}$ & $-$6.55$^{***}$ & $-$5.04$^{**}$ & $-$6.42$^{***}$ \\ 
  & (2.55) & (2.62) & (2.57) & (1.90) & (2.00) & (1.69) \\ 
  & & & & & & \\ 
 DiffAddress & 6.93$^{***}$ & 5.02$^{***}$ & 4.72$^{***}$ & 3.40$^{***}$ & 4.63$^{***}$ & 3.86$^{***}$ \\ 
  & (1.50) & (1.71) & (1.60) & (0.88) & (1.03) & (0.95) \\ 
  & & & & & & \\ 
 Distributive & 1.65 & 2.76$^{**}$ & 2.88$^{**}$ & 2.25$^{**}$ & 2.75$^{**}$ & 1.67 \\ 
  & (1.17) & (1.25) & (1.30) & (1.02) & (1.13) & (1.08) \\ 
  & & & & & & \\ 
 Extractive & 6.81$^{***}$ & 6.09$^{***}$ & 6.97$^{***}$ & 5.81$^{***}$ & 5.31$^{***}$ & 4.69$^{***}$ \\ 
  & (1.31) & (1.42) & (1.48) & (1.16) & (1.23) & (1.36) \\ 
  & & & & & & \\ 
 Indigenous & 4.47$^{***}$ & 6.12$^{***}$ & 5.90$^{***}$ & 6.81$^{***}$ & 5.62$^{***}$ & 3.97$^{***}$ \\ 
  & (1.38) & (1.49) & (1.49) & (1.17) & (1.35) & (1.26) \\ 
  & & & & & & \\ 
 Islam & 2.64 & 1.20 & $-$1.04 & $-$1.21 & 0.61 & 0.15 \\ 
  & (1.72) & (1.71) & (1.94) & (1.80) & (2.00) & (2.03) \\ 
  & & & & & & \\ 
 Judaism & 1.96$^{***}$ & 1.60$^{*}$ & 0.46 & 0.01 & 1.74 & 1.02 \\ 
  & (0.71) & (0.85) & (1.05) & (1.00) & (1.26) & (1.38) \\ 
  & & & & & & \\ 
 ManagerAdminClericalSales & 4.62$^{***}$ & 3.99$^{***}$ & 4.32$^{***}$ & 5.21$^{***}$ & 3.28$^{***}$ & 2.10$^{***}$ \\ 
  & (1.03) & (0.99) & (1.00) & (0.78) & (0.85) & (0.70) \\ 
  & & & & & & \\ 
 Married & $-$1.39 & 1.46 & 5.07$^{*}$ & 5.06$^{*}$ & 5.50$^{**}$ & 2.27 \\ 
  & (2.64) & (2.71) & (2.91) & (2.59) & (2.79) & (2.26) \\ 
  & & & & & & \\ 
 MedianAge & 2.94$^{*}$ & 2.28 & 2.08 & 1.86 & 3.73$^{**}$ & 1.54 \\ 
  & (1.63) & (1.88) & (2.08) & (1.65) & (1.55) & (1.30) \\ 
  & & & & & & \\ 
 NoReligion & 5.76$^{**}$ & 3.53 & 0.25 & $-$0.31 & 3.43 & 1.06 \\ 
  & (2.59) & (2.58) & (2.98) & (2.90) & (3.45) & (3.85) \\ 
  & & & & & & \\ 
 OneParent\_House & $-$0.85 & 0.11 & 0.22 & 1.66 & 1.37 & $-$1.00 \\ 
  & (1.39) & (1.46) & (1.61) & (1.38) & (1.49) & (1.34) \\ 
  & & & & & & \\ 
 OtherLanguageHome & 1.27 & $-$4.69 & $-$4.37 & $-$6.02 & $-$6.76 & $-$10.40$^{**}$ \\ 
  & (4.95) & (5.50) & (5.70) & (4.44) & (5.61) & (4.97) \\ 
  & & & & & & \\ 
 SocialServ & 2.90$^{***}$ & 0.94 & 1.91 & 1.77 & 1.89 & 2.42$^{*}$ \\ 
  & (1.10) & (1.22) & (1.35) & (1.14) & (1.27) & (1.27) \\ 
  & & & & & & \\ 
 Transformative & 4.75$^{***}$ & 3.74$^{**}$ & 3.28$^{*}$ & 5.20$^{***}$ & 5.74$^{***}$ & 2.99$^{**}$ \\ 
  & (1.41) & (1.57) & (1.74) & (1.47) & (1.59) & (1.41) \\ 
  & & & & & & \\ 
 Education & $-$3.04 & $-$0.90 & $-$1.82 & $-$0.77 & 1.94 & 0.62 \\ 
  & (2.99) & (3.04) & (3.35) & (2.89) & (2.86) & (2.23) \\ 
  & & & & & & \\ 
 FamHouseSize & $-$4.35 & $-$6.16$^{*}$ & $-$8.22$^{**}$ & $-$9.67$^{***}$ & $-$5.11$^{*}$ & $-$2.94 \\ 
  & (2.86) & (3.15) & (3.28) & (2.66) & (2.78) & (2.27) \\ 
  & & & & & & \\ 
 PropertyOwned & 1.76 & 0.68 & $-$1.17 & 0.78 & $-$0.92 & $-$0.76 \\ 
  & (1.38) & (1.43) & (1.49) & (1.09) & (1.21) & (1.19) \\ 
  & & & & & & \\ 
 RentLoanPrice & $-$0.70 & 1.01 & 2.12 & $-$0.54 & $-$1.54 & $-$0.31 \\ 
  & (2.02) & (1.96) & (1.96) & (1.48) & (1.68) & (1.50) \\ 
  & & & & & & \\ 
 Incomes & 8.46$^{***}$ & 4.19 & 2.73 & 4.36$^{*}$ & 2.95 & 2.99$^{*}$ \\ 
  & (2.57) & (2.68) & (3.06) & (2.56) & (2.60) & (1.76) \\ 
  & & & & & & \\ 
 Unemployment & 0.36 & $-$1.22 & $-$2.42 & $-$2.88$^{**}$ & $-$5.09$^{***}$ & $-$3.00$^{**}$ \\ 
  & (1.42) & (1.54) & (1.73) & (1.41) & (1.51) & (1.28) \\ 
  & & & & & & \\ 
 Constant & 50.45$^{***}$ & 53.48$^{***}$ & 49.92$^{***}$ & 47.32$^{***}$ & 52.63$^{***}$ & 50.78$^{***}$ \\ 
  & (0.74) & (0.56) & (0.51) & (0.35) & (0.45) & (0.67) \\ 
  & & & & & & \\ 
\hline \\[-1.8ex] 
Observations & 150 & 150 & 150 & 150 & 150 & 150 \\ 
Log Likelihood & $-$399.52 & $-$405.41 & $-$418.08 & $-$398.73 & $-$403.34 & $-$398.33 \\ 
Akaike Inf. Crit. & 863.03 & 874.83 & 900.16 & 861.46 & 870.68 & 860.67 \\ 
Bayesian Inf. Crit. & 951.96 & 963.76 & 989.10 & 950.40 & 959.61 & 949.60 \\ 
\hline 
\hline \\[-1.8ex] 
\textit{Note:}  & \multicolumn{6}{l}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
 & \multicolumn{6}{l}{Estimated coefficients for variable named in column one shown for} \\ 
 & \multicolumn{6}{l}{election year indicated by column heading, with estimated standard} \\ 
 & \multicolumn{6}{l}{deviation for each coefficient shown below in parenthesis. Overall} \\ 
 & \multicolumn{6}{l}{summary measures for each regression equation are provided in the} \\ 
 & \multicolumn{6}{l}{bottom panel.} \\
\end{tabular} 
\end{table} 
